version: "3.8"

services:
  promtail:
    image: grafana/promtail:2.6.1
    container_name: promtail
    volumes:
      - ./logs:/var/logs/
      - ./promtail:/etc/promtail/
    links:
      - loki
    command: -config.file=/etc/promtail/promtail.yml

  loki:
    image: grafana/loki:2.6.1
    container_name: loki
    volumes:
      - ./loki:/etc/loki/
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml

  grafana:
    image: grafana/grafana:9.0.3
    container_name: grafana
    links:
      - loki
    ports:
      - "3000:3000"