version: "3"

services:
  loki:
    image: grafana/loki:2.2.1
    container_name: loki-service
    volumes:
      - ./loki:/etc/loki/
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml

  promtail:
    image: grafana/promtail:2.2.1
    container_name: promtail-service
    volumes:
      - ./log:/var/log/
      - ./promtail:/etc/promtail/
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-service
    ports:
      - "3000:3000"